<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Carbon\Carbon;

class CreateMenusTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('menus', function (Blueprint $table) {
            $table->engine = 'InnoDB';
            $table->smallInteger('id')->unsigned()->autoIncrement();
            $table->smallInteger('modulo_id')->unsigned()->nullable();
            $table->smallInteger('menu_dependiente_id')->unsigned()->nullable();
            $table->string('nombre_visible', 50)->nullable();
            $table->string('url', 50)->nullable();
            $table->boolean('visible')->nullable()->unsigned();
            $table->smallInteger('orden')->default(1)->nullable()->unsigned();
            $table->string('class_name', 100)->nullable();
            $table->string('icono', 50)->nullable();
            $table->boolean('activo')->default(1)->nullable();
            $table->string('usercreated', 250)->nullable();
            $table->string('usermodifed', 250)->nullable();
            $table->timestamps();
        });

        Schema::table('menus', function (Blueprint $table) {
            $table->foreign('modulo_id')
                  ->references('id')
                  ->on('modulos')
                  ->onDelete('cascade');

            $table->foreign('menu_dependiente_id')
                  ->references('id')
                  ->on('menus')
                  ->onDelete('cascade');
        });

        $data = [
            [
                'modulo_id' => 1,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Página principal',
                'url' => 'home',
                'visible' => true,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-desktop',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => null,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Catálogos',
                'url' => null,
                'visible' => true,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 2,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Empresa',
                'url' => 'empresa',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => false,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 3,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Sucursales',
                'url' => 'sucursales',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => false,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 4,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Gestión de usuarios',
                'url' => null,
                'visible' => true,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 4,
                'menu_dependiente_id' => 5,
                'nombre_visible' => 'Usuarios',
                'url' => 'usuarios',
                'visible' => true,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-user',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 5,
                'menu_dependiente_id' => 5,
                'nombre_visible' => 'Asignación de usuario',
                'url' => 'asignacion-usuario',
                'visible' => true,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 8,
                'menu_dependiente_id' => 5,
                'nombre_visible' => 'Roles',
                'url' => 'roles',
                'visible' => true,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 9,
                'menu_dependiente_id' => 5,
                'nombre_visible' => 'Tipos de usuario',
                'url' => 'tipo-usuario',
                'visible' => true,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 8,
                'menu_dependiente_id' => 8,
                'nombre_visible' => 'RolAccion',
                'url' => 'rol-accion',
                'visible' => false,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 6,
                'menu_dependiente_id' => 7,
                'nombre_visible' => 'Usuarios por sucursal',
                'url' => 'usuario-sucursal',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 7,
                'menu_dependiente_id' => 11,
                'nombre_visible' => 'Roles por usuario',
                'url' => 'rol-usuario',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 7,
                'menu_dependiente_id' => 11,
                'nombre_visible' => 'Roles por usuario acción',
                'url' => 'rol-usuario-accion',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 10,
                'menu_dependiente_id' => 9,
                'nombre_visible' => 'Roles por tipo de usuario',
                'url' => 'rol-tipo-usuario',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-th-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 11,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Congresistas',
                'url' => 'congresistas',
                'visible' => false,
                'orden' => 5,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-users',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],

            [
                'modulo_id' => 11,
                'menu_dependiente_id' => 15,
                'nombre_visible' => 'Congresistas crear',
                'url' => 'congresistas-crear',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-users',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 11,
                'menu_dependiente_id' => 15,
                'nombre_visible' => 'Congresistas editar',
                'url' => 'congresistas-editar',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-users',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 12,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Comisiones y Plenos',
                'url' => 'comisiones',
                'visible' => true,
                'orden' => 6,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-university',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 12,
                'menu_dependiente_id' => 18,
                'nombre_visible' => 'Comisiones editar',
                'url' => 'comision-editar',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-university',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 13,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Proyectos',
                'url' => 'proyectos-ley',
                'visible' => true,
                'orden' => 7,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-book',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 13,
                'menu_dependiente_id' => 20,
                'nombre_visible' => 'Proyectos de ley crear',
                'url' => 'proyecto-ley-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-book',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 13,
                'menu_dependiente_id' => 20,
                'nombre_visible' => 'Proyectos de ley editar',
                'url' => 'proyecto-ley-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-book',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 14,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Nuestra democracia',
                'url' => 'blog-nd',
                'visible' => false,
                'orden' => 8,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-rss',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 14,
                'menu_dependiente_id' => 23,
                'nombre_visible' => 'Nuestra democracia crear',
                'url' => 'blog-nd-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-rss',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 14,
                'menu_dependiente_id' => 23,
                'nombre_visible' => 'Nuestra democracia editar',
                'url' => 'blog-nd-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-rss',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Congreso visible',
                'url' => 'congreso-visible',
                'visible' => false,
                'orden' => 9,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible editar',
                'url' => 'editar-congreso-visible',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible equipo',
                'url' => 'equipo-congreso-visible',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible aliado',
                'url' => 'aliado-congreso-visible',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - crear equipo',
                'url' => 'equipo-crear',
                'visible' => false,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - editar equipo',
                'url' => 'equipo-editar',
                'visible' => false,
                'orden' => 5,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - integrante equipo',
                'url' => 'integrante-equipo',
                'visible' => false,
                'orden' => 6,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - integrante equipo crear',
                'url' => 'integrante-crear',
                'visible' => false,
                'orden' => 7,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - integrante equipo editar',
                'url' => 'integrante-editar',
                'visible' => false,
                'orden' => 8,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - aliado crear',
                'url' => 'aliado-crear',
                'visible' => false,
                'orden' => 9,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 15,
                'menu_dependiente_id' => 26,
                'nombre_visible' => 'Congreso visible - aliado editar',
                'url' => 'aliado-editar',
                'visible' => false,
                'orden' => 10,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-building',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Control político',
                'url' => 'control-politico',
                'visible' => false,
                'orden' => 10,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político crear',
                'url' => 'control-politico-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político editar',
                'url' => 'control-politico-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político cuestionarios',
                'url' => 'control-politico-cuestionarios',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político gacetas',
                'url' => 'control-politico-gacetas',
                'visible' => false,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político respuestas',
                'url' => 'control-politico-respuestas',
                'visible' => false,
                'orden' => 5,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político citantes',
                'url' => 'control-politico-citantes',
                'visible' => false,
                'orden' => 6,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 16,
                'menu_dependiente_id' => 37,
                'nombre_visible' => 'Control político citados',
                'url' => 'control-politico-citados',
                'visible' => false,
                'orden' => 7,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Agenda legislativa',
                'url' => 'agenda-legislativa',
                'visible' => true,
                'orden' => 11,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-calendar-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => 45,
                'nombre_visible' => 'Agenda legislativa crear',
                'url' => 'agenda-legislativa-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-calendar-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => 45,
                'nombre_visible' => 'Agenda legislativa editar',
                'url' => 'agenda-legislativa-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-calendar-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 18,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Secretarios',
                'url' => 'secretarios',
                'visible' => false,
                'orden' => 12,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 18,
                'menu_dependiente_id' => 48,
                'nombre_visible' => 'Secretarios crear',
                'url' => 'secretarios-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 18,
                'menu_dependiente_id' => 48,
                'nombre_visible' => 'Secretarios editar',
                'url' => 'secretarios-editar',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 19,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Información del sitio',
                'url' => 'informacion-del-sitio',
                'visible' => false,
                'orden' => 13,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 19,
                'menu_dependiente_id' => 51,
                'nombre_visible' => 'Información del sitio crear',
                'url' => 'crear-informacion',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 19,
                'menu_dependiente_id' => 51,
                'nombre_visible' => 'Información del sitio editar',
                'url' => 'editar-informacion',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => null,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Contenido múltimedia',
                'url' => '',
                'visible' => false,
                'orden' => 14,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 20,
                'menu_dependiente_id' => 54,
                'nombre_visible' => 'Informes Regionales',
                'url' => 'informes-regionales',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-file-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 20,
                'menu_dependiente_id' => 55,
                'nombre_visible' => 'Informes PNUD documentos',
                'url' => 'informe-documentos',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-file-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 21,
                'menu_dependiente_id' => 54,
                'nombre_visible' => 'Balance cuatrienio',
                'url' => 'balances-cuatrienio',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 21,
                'menu_dependiente_id' => 57,
                'nombre_visible' => 'Balance cuatrienio crear',
                'url' => 'balances-cuatrienio-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 21,
                'menu_dependiente_id' => 57,
                'nombre_visible' => 'Balance cuatrienio editar',
                'url' => 'balances-cuatrienio-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 21,
                'menu_dependiente_id' => 57,
                'nombre_visible' => 'Balance cuatrienio informe',
                'url' => 'balances-cuatrienio-informes',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 21,
                'menu_dependiente_id' => 57,
                'nombre_visible' => 'Balance cuatrienio informe crear',
                'url' => 'balances-cuatrienio-informe-crear',
                'visible' => false,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 21,
                'menu_dependiente_id' => 57,
                'nombre_visible' => 'Balance cuatrienio informe editar',
                'url' => 'balances-cuatrienio-informe-editar',
                'visible' => false,
                'orden' => 5,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-balance-scale',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 22,
                'menu_dependiente_id' => 54,
                'nombre_visible' => 'Opinión',
                'url' => 'opinion',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 22,
                'menu_dependiente_id' => 63,
                'nombre_visible' => 'Opinión crear',
                'url' => 'opinion-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 22,
                'menu_dependiente_id' => 63,
                'nombre_visible' => 'Opinión editar',
                'url' => 'opinion-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 23,
                'menu_dependiente_id' => 54,
                'nombre_visible' => 'Opinión de congresistas',
                'url' => 'opinion-congresista',
                'visible' => false,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 23,
                'menu_dependiente_id' => 66,
                'nombre_visible' => 'Opinión de congresistas crear',
                'url' => 'opinion-congresista-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 23,
                'menu_dependiente_id' => 66,
                'nombre_visible' => 'Opinión de congresistas editar',
                'url' => 'opinion-congresista-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 24,
                'menu_dependiente_id' => 54,
                'nombre_visible' => 'Podcast',
                'url' => 'podcast',
                'visible' => false,
                'orden' => 5,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-microphone-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 24,
                'menu_dependiente_id' => 69,
                'nombre_visible' => 'Podcast crear',
                'url' => 'podcast-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-microphone-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 24,
                'menu_dependiente_id' => 69,
                'nombre_visible' => 'Podcast editar',
                'url' => 'podcast-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-microphone-alt',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 25,
                'menu_dependiente_id' => 54,
                'nombre_visible' => 'Multimedia',
                'url' => 'multimedia',
                'visible' => false,
                'orden' => 6,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 25,
                'menu_dependiente_id' => 72,
                'nombre_visible' => 'Multimedia crear',
                'url' => 'multimedia-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 25,
                'menu_dependiente_id' => 72,
                'nombre_visible' => 'Multimedia editar',
                'url' => 'multimedia-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-photo-video',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => null,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Actividades legislativas',
                'url' => '',
                'visible' => false,
                'orden' => 15,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 26,
                'menu_dependiente_id' => 75,
                'nombre_visible' => 'Partidos',
                'url' => 'partidos',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 26,
                'menu_dependiente_id' => 76,
                'nombre_visible' => 'Partidos crear',
                'url' => 'partidos-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 26,
                'menu_dependiente_id' => 76,
                'nombre_visible' => 'Partidos editar',
                'url' => 'partidos-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 27,
                'menu_dependiente_id' => 75,
                'nombre_visible' => 'Votaciones',
                'url' => 'votaciones',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 27,
                'menu_dependiente_id' => 79,
                'nombre_visible' => 'Votaciones crear',
                'url' => 'crear-votacion',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 27,
                'menu_dependiente_id' => 79,
                'nombre_visible' => 'Votaciones editar',
                'url' => 'editar-votacion',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 27,
                'menu_dependiente_id' => 79,
                'nombre_visible' => 'Votar',
                'url' => 'votar',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 28,
                'menu_dependiente_id' => 75,
                'nombre_visible' => 'Elecciones',
                'url' => 'elecciones',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 28,
                'menu_dependiente_id' => 83,
                'nombre_visible' => 'Elecciones crear',
                'url' => 'elecciones-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 28,
                'menu_dependiente_id' => 83,
                'nombre_visible' => 'Elecciones editar',
                'url' => 'elecciones-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 29,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Datos de contacto',
                'url' => 'datos-contacto',
                'visible' => true,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 30,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Cuatrienio',
                'url' => 'cuatrienio',
                'visible' => true,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 31,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Departamento',
                'url' => 'departamento',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 32,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Geografía',
                'url' => 'geografia',
                'visible' => false,
                'orden' => 4,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 33,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Género',
                'url' => 'generos',
                'visible' => true,
                'orden' => 5,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 34,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Grado de estudios',
                'url' => 'grado-estudios',
                'visible' => true,
                'orden' => 6,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 35,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Grupo de edad',
                'url' => 'grupo-de-edad',
                'visible' => true,
                'orden' => 7,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 36,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Circunscripción',
                'url' => 'circunscripcion',
                'visible' => false,
                'orden' => 8,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 37,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Cargos legislativos',
                'url' => 'cargo',
                'visible' => true,
                'orden' => 9,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 38,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Cargo de integrante',
                'url' => 'cargo-integrante',
                'visible' => false,
                'orden' => 10,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 39,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Estado de proyecto de ley',
                'url' => 'estado-proyecto-ley',
                'visible' => true,
                'orden' => 11,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 40,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Iniciativa',
                'url' => 'iniciativas',
                'visible' => true,
                'orden' => 12,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 41,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Legislatura',
                'url' => 'legislaturas',
                'visible' => true,
                'orden' => 13,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 42,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tema de proyecto de ley',
                'url' => 'tema-proyecto-ley',
                'visible' => true,
                'orden' => 14,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 43,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tema de control político',
                'url' => 'tema-control-politico',
                'visible' => false,
                'orden' => 15,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 44,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tipo de publicación proyecto de ley',
                'url' => 'tipo-publicacion-proyecto-ley',
                'visible' => false,
                'orden' => 16,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 45,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tipo de fecha proyecto de ley',
                'url' => 'tipo-fecha-proyecto-ley',
                'visible' => false,
                'orden' => 17,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 46,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Estado de control político',
                'url' => 'estado-control-politico',
                'visible' => true,
                'orden' => 18,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 47,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Glosario legislativo',
                'url' => 'glosario-legislativo',
                'visible' => false,
                'orden' => 19,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 48,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tema blog nuestra democracia',
                'url' => 'tema-blog-nuestra-democracia',
                'visible' => false,
                'orden' => 20,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 49,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tipo de actividad en la agenda legislativa',
                'url' => 'tipo-actividad-agenda-legislativa',
                'visible' => true,
                'orden' => 21,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 50,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Corporación',
                'url' => 'corporacion',
                'visible' => false,
                'orden' => 22,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 50,
                'menu_dependiente_id' => 107,
                'nombre_visible' => 'Corporación editar',
                'url' => 'corporacion-editar',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 51,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tipo citación',
                'url' => 'tipoCitacion',
                'visible' => false,
                'orden' => 23,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => 45,
                'nombre_visible' => 'Agenda legislativa actividades',
                'url' => 'agenda-legislativa-actividades',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => 45,
                'nombre_visible' => 'Agenda legislativa actividades crear',
                'url' => 'agenda-legislativa-actividades-crear',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => 45,
                'nombre_visible' => 'Agenda legislativa actividades editar',
                'url' => 'agenda-legislativa-actividades-editar',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],

            [
                'modulo_id' => 52,
                'menu_dependiente_id' => null,
                'nombre_visible' => 'Diputados',
                'url' => 'personas',
                'visible' => true,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-users',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 52,
                'menu_dependiente_id' => 113,
                'nombre_visible' => 'Crear persona',
                'url' => 'persona-crear',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 52,
                'menu_dependiente_id' => 113,
                'nombre_visible' => 'Editar persona',
                'url' => 'persona-editar',
                'visible' => false,
                'orden' => 2,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 53,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Profesión',
                'url' => 'profesion',
                'visible' => true,
                'orden' => 24,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 54,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Municipios',
                'url' => 'regiones',
                'visible' => true,
                'orden' => 25,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 55,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Departamento',
                'url' => 'municipios',
                'visible' => true,
                'orden' => 26,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 56,
                'menu_dependiente_id' => 2,
                'nombre_visible' => 'Tipo de investigacion',
                'url' => 'tipo-investigacion',
                'visible' => false,
                'orden' => 27,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 11,
                'menu_dependiente_id' => 15,
                'nombre_visible' => 'Congresistas por cuatrienio',
                'url' => 'congresistas-por-cuatrienio',
                'visible' => false,
                'orden' => 1,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-users',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ],
            [
                'modulo_id' => 17,
                'menu_dependiente_id' => 45,
                'nombre_visible' => 'Agenda legislativa Comision',
                'url' => 'agenda-legislativa-comision',
                'visible' => false,
                'orden' => 3,
                'class_name' => 'xn-text',
                'icono' => 'fa fa-list',
                'activo' => true,
                'usercreated' => 'sys@admin.com',
                'created_at' => Carbon::now()
            ]
        ];

        DB::table('menus')->insert($data);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('menus');
    }
}
